/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _PrismaMigrations {
  applied_steps_count: Generated<number>;
  checksum: string;
  finished_at: Timestamp | null;
  id: string;
  logs: string | null;
  migration_name: string;
  rolled_back_at: Timestamp | null;
  started_at: Generated<Timestamp>;
}

export interface Posts {
  created_at: Generated<Timestamp>;
  id: string;
  title: string;
  updated_at: Timestamp;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: string;
  is_admin: Generated<boolean>;
  password: string;
  updated_at: Timestamp;
}

export interface DB {
  _prisma_migrations: _PrismaMigrations;
  posts: Posts;
  users: Users;
}
